### ISSUE TITLE
Fatal error on fresh install when using a post_meta container

### ISSUE THREAD

**Issue by moxxuk** [matepaiva/wp-graphql-crb#6]
I get an error on a fresh install of this package in my plugin. I never used to, the only thing I've done is upgraded WP GraphQL to 1.2.5. In GraphiQL, I get:

```json
{
  "code": "internal_server_error",
  "message": "<p>There has been a critical error on this website.</p><p><a href=\"https://wordpress.org/support/article/debugging-in-wordpress/\">Learn more about debugging in WordPress.</a></p>",
  "data": {
    "status": 500
  },
  "additional_errors": []
}
```

Inspecting the debug log, I see:
```
[08-Mar-2021 15:00:46 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 203
[08-Mar-2021 15:00:46 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 203
[08-Mar-2021 15:00:46 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 203
[08-Mar-2021 15:00:46 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 203
[08-Mar-2021 15:00:46 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 203
[08-Mar-2021 15:00:46 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 203
[08-Mar-2021 15:00:46 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 203
[08-Mar-2021 15:00:46 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to register_graphql_field() must be of the type string, null given, called in /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php on line 47 and defined in /var/www/html/wpgraphql_crb_test/wp-content/plugins/wp-graphql/access-functions.php:269
Stack trace:
#0 /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php(47): register_graphql_field()
#1 /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php(63): WpGraphQLCrb\Container->registerField()
#2 /var/www/html/wpgraphql_crb_test/wp-content/plugins/graphql-carbon-test/vendor/matepaiva/wp-graphql-crb/src/Container.php(57): WpGraphQLCrb\Container->registerFields()
#3 /var/www/html/wpgraphql_crb_test/wp-includes/class-wp-hook.php(287): WpGraphQLCrb\Container->graphqlRegisterTypes()
#4 /var/www/html/wpgraphql_crb_test/wp-inclu in /var/www/html/wpgraphql_crb_test/wp-content/plugins/wp-graphql/access-functions.php on line 269
```

And digging deeper, I find that for the WpGraphQLCrb\Container instance, the `getGraphQLRoot()` method is returning:
```
Array
(
    [0] => post
    [1] => page
    [2] => mediaItem
    [3] => 
    [4] => 
    [5] => 
    [6] => 
    [7] => 
    [8] => 
    [9] => 
)
```

This array is mapped from `Carbon_Fields\REST_API\Decorator::get_post_meta_container_settings()` using the map function `$type` -> `getGraphQLPostTypeRoot($type)`. The array provided from that mapping is:

```
Array
(
    [0] => post
    [1] => page
    [2] => attachment
    [3] => revision
    [4] => nav_menu_item
    [5] => custom_css
    [6] => customize_changeset
    [7] => oembed_cache
    [8] => user_request
    [9] => wp_block
)
```

So it seems that `Container->getGraphQLPostTypeRoot($type)` is failing for `revision`, `nav_menu_item`, `custom_css`... etc, as those post type objects don't have a `graphql_single_name`.

My composer json:
```json
{
    "require": {
        "htmlburger/carbon-fields": "^3.2",
        "matepaiva/wp-graphql-crb": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Installed plugins: ```WP GraphQL (Version 1.2.5)```

My code:
```php
<?php
/*
Plugin Name: WPGraphQL Carbon Fields Test
Version: 1.0
*/

namespace GraphQLCarbonTest;

use WpGraphQLCrb\Container as WpGraphQLCrbContainer;
use Carbon_Fields\Container;
use Carbon_Fields\Field;

add_action( 'carbon_fields_register_fields', 'GraphQLCarbonTest\crb_attach_theme_options' );
function crb_attach_theme_options() {
	WpGraphQLCrbContainer::register(
    Container::make( 'post_meta', __( 'Test Post Meta Container' ) )
        ->add_fields( array(
            Field::make( 'text', 'crb_text', 'Text Field' ),
            // Field::make( 'icon', 'sm_download_icon', __( 'Icon', 'crb' ) ),
        ) )
	);
}

add_action( 'after_setup_theme', 'GraphQLCarbonTest\crb_load' );
function crb_load() {
    require_once( 'vendor/autoload.php' );
    \Carbon_Fields\Carbon_Fields::boot();
}
```

I'm thinking that removing these types from the `$roots` whose post type objects don't have a `graphql_single_name` would solve the issue, but I'm not confident that it wouldn't break anything else. What do you think?

**Comment by matepaiva** [comment]
I understand the problem and I think it is easy to fix.

So, if they do not have a graphql single name, they are useless for the plugin, right? In that case, I think we can just ignore them.

The way I think we can do it:
1. add a validation to `getGraphQLPostTypeRoot` and `getGraphQLTermTypeRoot` to avoid accessing that undefined property. I think that `isset($post_type_object->graphql_single_name) ? $post_type_object->graphql_single_name : ''` would be enough.
1. add an `array_filter` wrapping `array_map` (line 182), so we can remove the empty graphql_single_name from the list.

Do you agree with that approach? If so, would you be willing to make this contribution and open a pull request?

Thank you!

**Comment by moxxuk** [comment]
Yeah, I think I'm in agreement. I was unsure whether ignoring them had any adverse side effects, but as you say, because they don't have a `graphql_single_name`, they probably can be ignored.

As for your points:

1. Yes, the validation sounds good to me
2. Rather than an array_filter with an array_map, I used an array_reduce to get the same effect:
```
    $roots = array_reduce($types, function ($gqlTypes, $type) {
      switch ($this->container->type) {
        case 'post_meta':
          $gqlType = $this->getGraphQLPostTypeRoot($type);
          break;
          
        case 'term_meta':
          $gqlType = $this->getGraphQLTermTypeRoot($type);
          break;
          
        case 'user_meta':
          $gqlType = 'User';
          break;

        default:
          $gqlType = 'Post';
      }

      if(!empty($gqlType)) {
        $gqlTypes[] = $gqlType;
      }

      return $gqlTypes;
    }, []);

    return $roots;
  }
```

I'll submit this PR in a couple of hours if that's cool - dinner time now :)

**Comment by matepaiva** [comment]
Perfect. Remember to pull the master before doing the modifications, because I merged another PR. Thank you!

**Comment by moxxuk** [comment]
I thought I had fetched the latest changes, but it appears I didn't. The PR should only bring in my changes though - it won't revert your recent merge.

**Comment by matepaiva** [comment]
Sorry, I don't understand what I need to do to fix this situation.

**Comment by matepaiva** [comment]
I guess you didn't see the review and comment I made in the PR. I think there is an error at line 221 :)

**Comment by moxxuk** [comment]
Haha you're quite right! I was just debugging that, I noticed my taxonomy custom fields weren't coming through anymore... you just solved it for me :) My bad!

**Comment by matepaiva** [comment]
Haha! I didn't want to change it because I was afraid that it could be working locally for you, somehow. But I am happy we solved it together. I will merge it now :)

**Comment by matepaiva** [comment]
New version available:
- release details: https://github.com/matepaiva/wp-graphql-crb/releases/tag/0.0.2
- packagist version: https://packagist.org/packages/matepaiva/wp-graphql-crb#0.0.2

Thank you for your contribution!
